import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=Deno.env.get("SUPABASE_URL")??"";
const K=Deno.env.get("SUPABASE_ANON_KEY")??"";
const GH=Deno.env.get("GITHUB_TOKEN")??Deno.env.get("GITHUB_PAT")??Deno.env.get("GITHUB_REPO_TOKEN")??"";
const REPO=Deno.env.get("AI_EDITORIAL_GITHUB_REPO")??"Syasu-pixel/my-site";
const PAGES_PROJECT=Deno.env.get("AI_EDITORIAL_CLOUDFLARE_PAGES_PROJECT")??"denkicontrol-preview";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info, x-supabase-api-version","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});

async function rpc(raw:string,name:string,args:any){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:"POST",headers:{Authorization:raw,apikey:K,"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(args)});const t=await r.text();if(!r.ok)throw new Error(`${name} ${r.status}: ${t.slice(0,700)}`);return t?JSON.parse(t):{}}
async function gh(path:string){if(!GH)throw new Error("GITHUB_REPO_TOKEN missing");const r=await fetch(`https://api.github.com/repos/${REPO}${path}`,{headers:{Authorization:`Bearer ${GH}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"}});const t=await r.text();if(!r.ok)throw new Error(`GitHub ${r.status} ${path}: ${t.slice(0,700)}`);return t?JSON.parse(t):{}}
async function updateCheckpoint(raw:string,id:string,state:any){return rpc(raw,"ai_editorial_builder_checkpoint",{p_command_id:id,p_stage:"preview_wait",p_state:state})}
function branchAlias(branch:string){return branch.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function cloudflarePreview(branch:string,articlePath:string){const alias=branchAlias(branch);const path=String(articlePath||"").replace(/^\/+/,"");return `https://${alias}.${PAGES_PROJECT}.pages.dev/${path}`}
async function reachable(url:string){try{const r=await fetch(url,{method:"GET",redirect:"follow",headers:{"User-Agent":"denkicontrol-ai-editorial-preview-probe","Cache-Control":"no-cache"}});return {ok:r.ok,status:r.status,noindex:(r.headers.get("x-robots-tag")||"").toLowerCase().includes("noindex"),final_url:r.url}}catch(e){return {ok:false,status:0,noindex:false,final_url:url,error:e instanceof Error?e.message:String(e)}}}
async function finalize(raw:string,id:string,st:any){await rpc(raw,"ai_editorial_command_patch",{p_command_id:id,p_status:"needs_human",p_last_error:null,p_mark_started:false});await rpc(raw,"ai_editorial_command_add_events",{p_command_id:id,p_events:[{event_id:crypto.randomUUID(),job_id:`command-${id}`,role:"reviewer",provider:"article-builder",event_type:"preview-ready",summary:"Cloudflare Pages Previewが完成しました。記事内容・表示・画像・リンク・HTMLソースを確認してから採用判断してください。",evidence:[{kind:"github-pr",ref:st.pr_url},{kind:"preview",ref:st.preview_url}],severity:"info",state:"NEEDS_HUMAN",created_at:new Date().toISOString(),discussion:{command_id:id,stage:"preview-ready",pr_number:st.pr_number,pr_url:st.pr_url,preview_url:st.preview_url,preview_provider:"cloudflare-pages",article_path:st.article_path,article_title:st.bp?.title,hero_score:st.hero_score,ogp_score:st.ogp_score,admin_gate:"preview-only",preview_verified_by:"http-preview-probe"},availability:{primary_provider:"article-builder",status:"waiting-human"}}]});await rpc(raw,"ai_editorial_builder_checkpoint",{p_command_id:id,p_stage:"done",p_state:{...st,preview_verified:true,preview_provider:"cloudflare-pages",preview_verified_at:new Date().toISOString()}})}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="POST")return J({error:"method not allowed"},405);const raw=req.headers.get("authorization")??"";if(!raw.toLowerCase().startsWith("bearer "))return J({error:"authentication required"},401);let input:any={};try{input=await req.json()}catch{return J({error:"invalid json"},400)}const id=String(input.command_id??"");if(!/^[0-9a-f-]{36}$/i.test(id))return J({error:"valid command_id required"},400);try{const st=input.state&&typeof input.state==="object"?input.state:{};const pr=Number(st.pr_number||0);if(!pr||!st.article_path)return J({ok:false,error:"preview metadata missing"},409);const p=await gh(`/pulls/${pr}`);const sha=String(p?.head?.sha||"");const branch=String(p?.head?.ref||st.branch||"");if(!sha||!branch)return J({ok:false,error:"PR head metadata missing"},409);const preview=cloudflarePreview(branch,st.article_path);const check=await reachable(preview);const checks=Number(st.preview_probe_checks||0)+1;const next={...st,branch,preview_url:preview,preview_provider:"cloudflare-pages",preview_probe_checks:checks,preview_last_status:check.ok?"success":String(check.status||"waiting"),preview_http_status:check.status,preview_noindex:check.noindex,preview_last_checked_at:new Date().toISOString(),preview_head_sha:sha};if(check.ok){await finalize(raw,id,next);return J({ok:true,status:"needs_human",preview_url:preview,pr_url:st.pr_url,noindex:check.noindex})}await updateCheckpoint(raw,id,next);return J({ok:true,status:"waiting",preview_url:preview,http_status:check.status,checks})}catch(e){return J({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
