import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const U=Deno.env.get("SUPABASE_URL")??"";
const K=Deno.env.get("SUPABASE_ANON_KEY")??"";
const GH=Deno.env.get("GITHUB_TOKEN")??Deno.env.get("GITHUB_PAT")??Deno.env.get("GITHUB_REPO_TOKEN")??"";
const REPO=Deno.env.get("AI_EDITORIAL_GITHUB_REPO")??"Syasu-pixel/my-site";
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-client-info, x-supabase-api-version","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};
const J=(b:unknown,s=200)=>new Response(JSON.stringify(b),{status:s,headers:H});

async function rpc(raw:string,name:string,args:any){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:"POST",headers:{Authorization:raw,apikey:K,"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify(args)});const t=await r.text();if(!r.ok)throw new Error(`${name} ${r.status}: ${t.slice(0,700)}`);return t?JSON.parse(t):{}}
async function gh(path:string){if(!GH)throw new Error("GITHUB_REPO_TOKEN missing");const r=await fetch(`https://api.github.com/repos/${REPO}${path}`,{headers:{Authorization:`Bearer ${GH}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"}});const t=await r.text();if(!r.ok)throw new Error(`GitHub ${r.status} ${path}: ${t.slice(0,700)}`);return t?JSON.parse(t):{}}
async function builderRun(raw:string,id:string){const r=await fetch(`${U}/rest/v1/ai_editorial_builder_runs?command_id=eq.${id}&select=stage,state&limit=1`,{headers:{Authorization:raw,apikey:K,Accept:"application/json"}});const t=await r.text();if(!r.ok)throw new Error(`builder run ${r.status}: ${t.slice(0,500)}`);const a=t?JSON.parse(t):[];return Array.isArray(a)?a[0]:null}
async function updateCheckpoint(raw:string,id:string,state:any){return rpc(raw,"ai_editorial_builder_checkpoint",{p_command_id:id,p_stage:"preview_wait",p_state:state})}
async function finalize(raw:string,id:string,st:any){await rpc(raw,"ai_editorial_command_patch",{p_command_id:id,p_status:"needs_human",p_last_error:null,p_mark_started:false});await rpc(raw,"ai_editorial_command_add_events",{p_command_id:id,p_events:[{event_id:crypto.randomUUID(),job_id:`command-${id}`,role:"reviewer",provider:"article-builder",event_type:"preview-ready",summary:"Previewが完成しました。記事内容・表示・画像・リンク・HTMLソースをGPTと一緒に確認してから採用判断してください。",evidence:[{kind:"github-pr",ref:st.pr_url},{kind:"netlify-preview",ref:st.preview_url}],severity:"info",state:"NEEDS_HUMAN",created_at:new Date().toISOString(),discussion:{command_id:id,stage:"preview-ready",pr_number:st.pr_number,pr_url:st.pr_url,preview_url:st.preview_url,article_path:st.article_path,article_title:st.bp?.title,hero_score:st.hero_score,ogp_score:st.ogp_score,admin_gate:"preview-only",preview_verified_by:"github-netlify-status"},availability:{primary_provider:"article-builder",status:"waiting-human"}}]});await rpc(raw,"ai_editorial_builder_checkpoint",{p_command_id:id,p_stage:"done",p_state:{...st,preview_verified:true,preview_verified_at:new Date().toISOString()}})}

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:H});if(req.method!=="POST")return J({error:"method not allowed"},405);const raw=req.headers.get("authorization")??"";if(!raw.toLowerCase().startsWith("bearer "))return J({error:"authentication required"},401);let input:any={};try{input=await req.json()}catch{return J({error:"invalid json"},400)}const id=String(input.command_id??"");if(!/^[0-9a-f-]{36}$/i.test(id))return J({error:"valid command_id required"},400);try{const run=await builderRun(raw,id);if(!run||run.stage!=="preview_wait")return J({ok:true,skipped:true,stage:run?.stage??null});const st=run.state&&typeof run.state==="object"?run.state:{};const pr=Number(st.pr_number||0);if(!pr||!st.preview_url)return J({ok:false,error:"preview metadata missing"},409);const p=await gh(`/pulls/${pr}`);const sha=String(p?.head?.sha||"");if(!sha)return J({ok:false,error:"PR head SHA missing"},409);const statuses=await gh(`/commits/${sha}/status`);const list=Array.isArray(statuses?.statuses)?statuses.statuses:[];const netlify=list.find((x:any)=>String(x?.context||"").includes("netlify/")&&String(x?.context||"").includes("deploy-preview"));const checks=Number(st.preview_probe_checks||0)+1;const next={...st,preview_probe_checks:checks,preview_last_status:netlify?.state??statuses?.state??"unknown",preview_last_checked_at:new Date().toISOString(),preview_head_sha:sha};if(netlify?.state==="success"){await finalize(raw,id,next);return J({ok:true,status:"needs_human",preview_url:st.preview_url,pr_url:st.pr_url})}await updateCheckpoint(raw,id,next);return J({ok:true,status:"waiting",netlify_status:netlify?.state??statuses?.state??"unknown",checks})}catch(e){return J({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
