from pathlib import Path
p=Path('.github/scripts/temp_build_equipment_v2.py')
s=p.read_text(encoding='utf-8')
s=s.replace("main_start=s.index('<div class=\"main\">', s.index('<div class=\"layout\">'))","main_start=s.index('<main class=\"main\">', s.index('<div class=\"layout\">'))")
s=s.replace("main='''<div class=\"main\">","main='''<main class=\"main\"><article>")
s=s.replace("        </section>\n      </div>\n\n      '''","        </section>\n      </article></main>\n\n      '''")
s=s.replace("aside_start=s.index('<aside class=\"side\">', main_start)","aside_start=s.index('<aside class=\"side\"', main_start)")
s=s.replace("aside_start=s.index('<aside class=\"side\">')","aside_start=s.index('<aside class=\"side\"')")
s=s.replace("aside='''<aside class=\"side\">","aside='''<aside class=\"side\" aria-label=\"補足情報\">")
s=s.replace("<section class=\"side-card support-card\">","<section class=\"side-card support-card\" aria-label=\"サイト応援\">")
p.write_text(s,encoding='utf-8')
print('patched build script for exact main/side structure')
