(()=>{'use strict';
 const config=JSON.parse(document.getElementById('dc-toc-data').textContent),en=config.lang==='en';
 const items=config.toc.filter(i=>document.getElementById(i.id));if(!items.length)return;
 const button=document.createElement('button');button.type='button';button.className='dc-toc-button';button.setAttribute('aria-haspopup','dialog');button.setAttribute('aria-controls','dc-toc-dialog');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label',en?'Open article contents':'この記事の目次を開く');
 button.innerHTML='<svg viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="M7 5h10M7 10h10M7 15h10M3 5h.1M3 10h.1M3 15h.1" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>'+(en?'Contents':'目次');
 const dialog=document.createElement('dialog');dialog.id='dc-toc-dialog';dialog.className='dc-toc-dialog';dialog.setAttribute('aria-labelledby','dc-toc-title');dialog.setAttribute('aria-describedby','dc-toc-description');
 const panel=document.createElement('div');panel.className='dc-toc-panel';dialog.append(panel);
 const mobile=window.matchMedia(`(max-width:${config.compactMaxWidth||1100}px)`);
 document.documentElement.classList.toggle('dc-toc-compact',mobile.matches);
 const head=document.createElement('div');head.className='dc-toc-head';head.innerHTML='<div><h2 id="dc-toc-title">'+(en?'Article contents':'この記事の目次')+'</h2><p id="dc-toc-description">'+(en?'Choose a section to continue reading':'読みたい項目を選んで移動')+'</p></div>';
 const close=document.createElement('button');close.type='button';close.className='dc-toc-close';close.textContent=en?'Close ×':'閉じる ×';head.append(close);panel.append(head);
 const list=document.createElement('ol');list.className='dc-toc-list';
 items.forEach((item,index)=>{const li=document.createElement('li'),a=document.createElement('a'),num=document.createElement('span');a.href='#'+encodeURIComponent(item.id);num.textContent=String(index+1).padStart(2,'0');a.append(num,document.createTextNode(item.label));li.append(a);list.append(li);a.addEventListener('click',e=>{e.preventDefault();finish(item.id);});});panel.append(list);document.body.append(button,dialog);
 // One shared list serves every viewport. Native modal makes background inert.
 let savedY=0,savedStyles=null;
 const properties=['position','top','left','right','width','overflow'];
 function clearance(){const h=document.querySelector('header.site-header');return Math.max(16,h?Math.max(0,h.getBoundingClientRect().bottom)+16:16);}
 function jump(id){const target=document.getElementById(id);if(!target)return;const h=target.matches('h2,h3')?target:target.querySelector('h2,h3')||target;h.classList.add('dc-toc-destination');const prior=h.getAttribute('tabindex');h.tabIndex=-1;h.focus({preventScroll:true});const top=Math.max(0,window.scrollY+h.getBoundingClientRect().top-clearance());const old=document.documentElement.style.scrollBehavior;document.documentElement.style.scrollBehavior='auto';window.scrollTo(0,top);document.documentElement.style.scrollBehavior=old;history.replaceState(null,'','#'+encodeURIComponent(id));h.addEventListener('blur',()=>{h.classList.remove('dc-toc-destination');if(prior===null)h.removeAttribute('tabindex');else h.setAttribute('tabindex',prior);},{once:true});}
 function unlock(){if(button.parentElement===dialog)dialog.before(button);if(!savedStyles)return;properties.forEach(p=>document.body.style[p]=savedStyles[p]);savedStyles=null;const old=document.documentElement.style.scrollBehavior;document.documentElement.style.scrollBehavior='auto';window.scrollTo(0,savedY);document.documentElement.style.scrollBehavior=old;button.setAttribute('aria-expanded','false');button.setAttribute('aria-label',en?'Open article contents':'この記事の目次を開く');}
 function finish(id){dialog.close();unlock();if(id)jump(id);else button.focus({preventScroll:true});}
 function openMode(){if(mobile.matches){dialog.append(button);button.focus({preventScroll:true});}else{dialog.before(button);close.focus({preventScroll:true});}}
 mobile.addEventListener('change',()=>{document.documentElement.classList.toggle('dc-toc-compact',mobile.matches);if(dialog.open)openMode();schedulePlace();});
 button.addEventListener('click',()=>{if(dialog.open){finish();return;}savedY=window.scrollY;savedStyles=Object.fromEntries(properties.map(p=>[p,document.body.style[p]]));Object.assign(document.body.style,{position:'fixed',top:`-${savedY}px`,left:'0',right:'0',width:'100%',overflow:'hidden'});button.setAttribute('aria-expanded','true');button.setAttribute('aria-label',en?'Close article contents':'この記事の目次を閉じる');const current=[...items].reverse().find(i=>document.getElementById(i.id).getBoundingClientRect().top<=clearance()+30)||items[0];list.querySelectorAll('a').forEach((a,i)=>{if(items[i].id===current.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});if(mobile.matches)dialog.append(button);dialog.showModal();openMode();});
 close.addEventListener('click',()=>finish());dialog.addEventListener('cancel',e=>{e.preventDefault();finish();});dialog.addEventListener('close',()=>{if(!dialog.open)unlock();});
 dialog.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();finish();}else if(e.key==='Tab'){const first=mobile.matches?list.querySelector('a'):close,last=mobile.matches?button:list.querySelector('li:last-child a');if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
 let outsideDown=false;const outside=e=>{const r=panel.getBoundingClientRect();return e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom;};dialog.addEventListener('pointerdown',e=>outsideDown=outside(e));dialog.addEventListener('click',e=>{if(e.target===dialog&&outsideDown&&outside(e))finish();outsideDown=false;});
 // Follow each source article's layout breakpoint, not the device name.
 // Wide: below search / expanded header panels. Compact: above bottom controls.
 const fixedBottom=[...document.querySelectorAll('footer,[data-fixed-footer],.fixed-footer,#scrollTopBtn')];
 const header=document.querySelector('header.site-header'),headerPanels=[...document.querySelectorAll('header .dc-drawer,header .search-box-panel,header .language-menu-panel')];
 function place(){if(dialog.open)return;const root=document.documentElement,b=button.getBoundingClientRect();if(!mobile.matches){const search=document.querySelector('#dc-search-toggle')||document.querySelector('.header-search');const r=search?.getBoundingClientRect();const right=Math.max(14,Math.min(innerWidth-b.width-14,r&&r.width?innerWidth-r.right:14));let top=Math.max(14,(header?.getBoundingClientRect().bottom||0)+12);const left=innerWidth-right-b.width;for(const el of headerPanels){const s=getComputedStyle(el),p=el.getBoundingClientRect();if(s.display!=='none'&&s.visibility!=='hidden'&&p.width&&p.height&&p.left<left+b.width&&p.right>left)top=Math.max(top,p.bottom+12);}root.style.setProperty('--dc-toc-top',Math.min(top,innerHeight-b.height-14)+'px');root.style.setProperty('--dc-toc-right',right+'px');return;}let reserve=20;for(const el of fixedBottom){const s=getComputedStyle(el),r=el.getBoundingClientRect();if(s.position==='fixed'&&s.visibility!=='hidden'&&r.width>0&&r.height>0&&r.top<innerHeight&&s.bottom!=='auto'&&r.left<b.right&&r.right>b.left)reserve=Math.max(reserve,innerHeight-r.top+12);}root.style.setProperty('--dc-toc-bottom',reserve+'px');}
 let placementFrame=0;function schedulePlace(){if(!placementFrame)placementFrame=requestAnimationFrame(()=>{placementFrame=0;place();});}
 place();window.addEventListener('resize',schedulePlace,{passive:true});window.addEventListener('scroll',schedulePlace,{passive:true});dialog.addEventListener('close',schedulePlace);
 if(header){new MutationObserver(schedulePlace).observe(header,{attributes:true,subtree:true,childList:true});const observer=new ResizeObserver(schedulePlace);observer.observe(header);headerPanels.forEach(el=>observer.observe(el));}
})();
