create table if not exists public.orchestrator_events (
  id bigint generated by default as identity primary key,
  event_id uuid not null unique,
  job_id text not null,
  role text not null check (role in ('editor','builder','challenger','reviewer','system','human','image-reviewer')),
  provider text not null,
  event_type text not null,
  summary text not null check (char_length(summary) <= 2000),
  evidence jsonb not null default '[]'::jsonb,
  severity text not null default 'info' check (severity in ('info','low','medium','high','blocker')),
  state text not null,
  created_at timestamptz not null,
  inserted_at timestamptz not null default now()
);
create index if not exists orchestrator_events_job_created_idx on public.orchestrator_events(job_id, created_at);
alter table public.orchestrator_events enable row level security;
revoke all on public.orchestrator_events from anon, authenticated;
comment on table public.orchestrator_events is 'Sanitized AI Editorial Dashboard events. Access only via ai-editorial-feed Edge Function.';
